### ISSUE TITLE
rumode testrun produces error with DESEQ2

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CARLISLE#113]
**Describe the bug**
Running the testrun runmode through the pipeline produces errors.

**To Reproduce**
```
bash carlisle --runmode=testrun --workdir=/data/sevillas2/carlisle
```

**Expected behavior**
The piepline should run to completion without this error.

**Comment by kelly-sovacool** [comment]
it's supposed to be `--runmode=runtest` instead of `testrun`, right?
