### ISSUE TITLE
deseq2 sample check is failingi

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CARLISLE#126]
**Describe the bug**
From Erica

> hi Sam, good morning! I'm still running into some DESeq2 issues with CARLISLE that I wanted to run by you. All of my conditions have at least 3-4 replicates, but (Sh2 vs PC) are failing during the check for single-sample groups, while the other half (Sh1 vs PC) are being treated as having a single sample and producing empty output files. I think this might be because they have a "1" in the group name. I'm going to comment out the check for my projects, but just wanted to let you know!

Will need to design a better way to determine samples vs groups

**Comment by epehrsson** [comment]
_diff_markdown_wrapper.R, line 90 - log2FC is being assigned FDR cutoff
