### ISSUE TITLE
T2T support

### ISSUE THREAD

**Issue by kopardev** [CCBR/CARLISLE#18]
Add support for T2T human assembly for CCRGB-5
- [Fasta](https://www.ncbi.nlm.nih.gov/assembly/GCA_009914755.4)
- Annotation??

**Comment by slsevilla** [comment]
https://www.ncbi.nlm.nih.gov/assembly/GCA_009914755.4

https://ccb.jhu.edu/T2T.shtml

**Comment by kopardev** [comment]
If you open that link in Finder you get something like this:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/1882209/213297671-c63ac4a5-270c-43c1-bb0f-fce5cf714999.png">
I can see the fasta file here, but the annotations are in GFF3 format and not GTF.

**Comment by kopardev** [comment]
Check [this](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/009/914/755/GCF_009914755.1_T2T-CHM13v2.0/) out! 
![image](https://user-images.githubusercontent.com/1882209/214333367-ea083b6a-83a0-4036-bbd5-9b5377a0a387.png)
This is probably what we want to use. (Fa+GTF)

**Comment by kopardev** [comment]
Just for reference the official CHM13 related download GH [repo](https://github.com/marbl/CHM13#downloads).

**Comment by slsevilla** [comment]
annotations downloaded: /data/CCBR_Pipeliner/db/PipeDB/Indices/T2T

**Comment by slsevilla** [comment]
Alignment results for HS1 are comparable with HG38 for test samples.
[hg38_vs_hs1.pdf](https://github.com/CCBR/CARLISLE/files/10561675/hg38_vs_hs1.pdf)

**Comment by slsevilla** [comment]
Run through annotations was deployed: 57654474

**Comment by slsevilla** [comment]
Deseq/deseq2 failed due to missing TXDB and annotation objects. Will need workaround.

**Comment by kopardev** [comment]
Tried to fix the TxDb error for hs1 ... try [this](https://github.com/CCBR/CARLISLE/tree/feature/txdb4hs1) branch... Let me know if it works.

**Comment by slsevilla** [comment]
combined VK and SSC merged for txdb - local run successful

Dry-run was successful .... submitting jobs to job-scheduler
Running...
57716781

**Comment by slsevilla** [comment]
txdb code merger was successful. Issue with txdb required additional code fixes:
- BSgenome for hs1 requires R > 4.2. Updated R version commit 05a1e6a965a6751c0df614b45592ae7b0b93c745
- ELBOW (rules for DESEQ) and GGVEN (rules for venn) are not compatible with this new version of R. download source code. commit fd8c78f6588c9fb29f646a41674b83c65762b7b6
- HS1 has different column headers than previous output (SYMBOL is named geneId). Updated code to change col names if geneId is found. commit fd8c78f6588c9fb29f646a41674b83c65762b7b6

With these changes DESEQ/DESEQ2/VENN rules all ran to completion

**Comment by slsevilla** [comment]
homer edits for hs1:
- homer requires different command for custom genome input; added new command and necessary params. commit fb642c61e49a68dd3c505c7c0e9ee4ce5985ea0e
- homer will create bin files to be used for future projects based on .fa name. current ref.fa naming schema for hs1 will not work. updating to hs1.fa. commit 250811e303d5651579fc55f2ba362e8dc70b12ff

**Comment by slsevilla** [comment]
rose edits for hs1:
- ROSE requires different command for custom genome input; added new command and necessary params. commit 5f7d1387aa6d25b4f8b989b9fba09a5de3f30748

**Comment by slsevilla** [comment]
Running rules with all peak callers and deduplication methods to ensure stability with new HS1 updates.

**Comment by slsevilla** [comment]
Testing is complete. Changes merged into dev branch
