### ISSUE TITLE
Motif Enrichment

### ISSUE THREAD

**Issue by kopardev** [CCBR/CARLISLE#19]
- [x] Get scripts from Khanlab ... append to pipeline
- [ ] Explore applicability of existing MOTIF enrichment rules/scripts from CCBR ChipSeq and ASAP pipelines

**Comment by kopardev** [comment]
Check out [https://github.com/CCBR/ASAP/blob/master/workflow/scripts/ccbr_atac_motif_enrichment.bash](https://github.com/CCBR/ASAP/blob/master/workflow/scripts/ccbr_atac_motif_enrichment.bash)

**Comment by slsevilla** [comment]
Hsien Chao’s chipseq pipeline code:
https://github.com/CCRGeneticsBranch/khanlab_pipeline/blob/master/rules/pipeline.chipseq.smk

Rules needed for annotation of carlisle output files
rule peakAnnotation
rule rose
rule findMotif
localrule prepareRoseSummit

**Comment by slsevilla** [comment]
rule peakAnnotation implemented - split into macs2 and seacar/gopeaks

**Comment by slsevilla** [comment]
rule rose and localrule prepareRoseSummit merged - complete for macs2

**Comment by slsevilla** [comment]
all rules are preliminary added - waiting for Yue to provide reference files and script files needed to complete motif analysis

**Comment by slsevilla** [comment]
Test run in progress- all annotation files have been added

**Comment by slsevilla** [comment]
Updated code to rose expected output. running test with samples now
Dry-run was successful .... submitting jobs to job-scheduler
Running...
56996459

**Comment by slsevilla** [comment]
rule successfully implemented in pipeline
