### ISSUE TITLE
MAPQ filter

### ISSUE THREAD

**Issue by kopardev** [CCBR/CARLISLE#54]
Add ![image](https://user-images.githubusercontent.com/1882209/225792910-95aef49d-4ef6-405a-89ab-636293636168.png) [here](https://github.com/CCBR/CARLISLE/blob/61249518bf7fd63603e2230d8dd3d098c34825d7/workflow/rules/align.smk#L92)

**Comment by slsevilla** [comment]
Notes on addition: 
Basically, the T2T genome has multitude of reads multimapping to the centromere region. These can be expelled by this “-q” filter thereby decreasing the skewedness in chromosome-wide coverage and improving peak calling performance.

Will add param to config + align rule.

**Comment by slsevilla** [comment]
-q flag: only report alignment records with mapping quality of at least N (>= N).
- f 0x2 flag: each segment properly aligned according to the aligner
