### ISSUE TITLE
Add `spooker` to track usage

### ISSUE THREAD

**Issue by kopardev** [CCBR/CARLISLE#80]
Heard from Erica that they (her group) is running CARLISLIE quite often. It will be good track statistics.

You can get inspiration from [RENEE](https://github.com/CCBR/RENEE/blob/e08f7db6c6e638cfd330caa182f64665d2ef37fa/workflow/Snakefile#L233)

**Comment by slsevilla** [comment]
created [feature/spook](https://github.com/CCBR/CARLISLE/tree/feature/spook) branch, added files with commit 14ae7844121a96d37ef7d06646f349b903d3fa62. performing test run now.

**Comment by slsevilla** [comment]
testing completed. merged into main
