### ISSUE TITLE
pipeline ending early, without completing tasks

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CARLISLE#9]
Pipeline is ending early, with rules still left to be completed. Dry-runs complete successfully and master job indicates "COMPLETE" while still having missing files:

| job | count | min threads | max threads |
| ----------- | ----------- | ----------- | ----------- |
| DESeq | 8 | 1 | 1 |
| DESeq2 | 8 | 1 | 1 |
| all | 1 | 1 | 1 |
| contrast_init |1 | 1 | 1 |
| diffbb | 8 | 1 | 1 |
| make_counts_matrix | 8 | 1 | 1 |
| make_inputs | 8 | 1 | 1 |
| venn | 8 | 1 | 1 |
| total | 50 | 1 | 1 |

**Comment by slsevilla** [comment]
Ran pipeline locally to find error and discovered the issue: 

```
cat: /vf/users/CCBR/projects/ccbr1155/CS031188_complete/results/bedgraph/CRISPR_KO_10_Smyd3_1.dedup.sf.yaml: No such file or directory
```

I had marked this sample as a "control" in the sample manifest: 
| sampleName |  replicateNumber |  isControl |  controlName |  controlReplicateNumber |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| CRISPR_NC_2_Smyd3 |  1 |  Y |  - |  1 |
| CRISPR_NC_2_Smyd3 |  2 |  Y |  - |  2 |
| CRISPR_NC_2_Smyd3 |  3 |  Y |  - |  3 |
| CRISPR_KO_10_Smyd3 |  1 |  Y |  - |  1 |
| CRISPR_KO_10_Smyd3 |  2 |  Y |  - |  2 |
| CRISPR_KO_10_Smyd3 |  3 |  Y |  - |  3 |

But included them in my contrast list:
| condition1 | condition2 |
| ----------- | ----------- | 
| CRISPR_NC_2_Smyd3| CRISPR_KO_10_Smyd3 |

.YAML files are not created for any control, and so when the pipeline went to pull these files, they did not exist. 

SHORT TERM SOLUTION: Fixed this by changing the samples status from 'control' to 'sample'. 

LONG TERM SOLUTION: Need to add a check during dry-run to ensure that contrasts are not listed as controls.

**Comment by kopardev** [comment]
`% grep "CRISPR_KO_10_Smyd3\|CRISPR_NC_2_Smyd3" /vf/users/CCBR/projects/ccbr1155/CS031188_complete/samples.tsv |cut -f1-3`
| sampleName            | replicateNumber | isControl |
| --------------------- | --------------- | --------- |
| CRISPR\_NC\_2\_Smyd3  | 1               | N         |
| CRISPR\_NC\_2\_Smyd3  | 2               | N         |
| CRISPR\_NC\_2\_Smyd3  | 3               | N         |
| CRISPR\_KO\_10\_Smyd3 | 1               | N         |
| CRISPR\_KO\_10\_Smyd3 | 2               | N         |
| CRISPR\_KO\_10\_Smyd3 | 3               | N         |
None of these are actually controls... The way you have it set up currently in `samples.tsv` is the right way. The `isControl` column is only for calling cut and run peaks ... It is like `Input` or `IgG` in chipseq, but contrast is like differential peak analysis in chipseq. ... None of these can be Control for the previous step, ie., peak calling. Does that make sense

**Comment by slsevilla** [comment]
Yep, I understood what it meant after going through this error. I was wrong in how I set it up. From: Vishal Koparde ***@***.***>Date: Tuesday, June 7, 2022 at 14:13To: CCBR/CARLISLE ***@***.***>Cc: Samantha ***@***.***>, Assign ***@***.***>Subject: Re: [CCBR/CARLISLE] pipeline ending early, without completing tasks (Issue #9)% grep "CRISPR_KO_10_Smyd3|CRISPR_NC_2_Smyd3" /vf/users/CCBR/projects/ccbr1155/CS031188_complete/samples.tsv |cut -f1-3sampleNamereplicateNumberisControlCRISPR_NC_2_Smyd31NCRISPR_NC_2_Smyd32NCRISPR_NC_2_Smyd33NCRISPR_KO_10_Smyd31NCRISPR_KO_10_Smyd32NCRISPR_KO_10_Smyd33NNone of these are actually controls... The way you have it set up currently in samples.tsv is the right way. The isControl column is only for calling cut and run peaks .. It is like Input or IgG in chipseq, but contrast is like differential peak analysis in chipseq. ... None of these can be Control for the previous step, ie., peak calling. Does that make sense—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by slsevilla** [comment]
completed with commit a52a160ae3eec51b9ca577be32c565556cae71b9
