### ISSUE TITLE
Add CARLISLE to CCBR_Pipeliner

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CARLISLE#90]
**Describe what enhancement you'd like to see.**
- [ ] Add new version to /data/CCBR_Pipeliner/Pipelines/guis/4/bin
- [ ] Add issue for CCBR_Pipeliner for version 5 / v2.5.0

**Comment by kelly-sovacool** [comment]
this was completed when ccbrpipeliner v5 was released https://github.com/CCBR/ccbrpipeliner/blob/5e211d9e9efaa330db1dd3b375d7ce6b45580675/modules/ccbrpipeliner/5.lua
