### ISSUE TITLE
Create install script

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/CARLISLE#91]
- Copy essential files + carlisle cli script to a designated directory (#93)
- Create a github action to ~install carlisle with this script and~ execute a dryrun (#94)

**Comment by slsevilla** [comment]
issues
- [ ] CARLISLE is not highlighted in selection
- [ ] annotation dir not copied (needed for ROSE execution)

**Comment by slsevilla** [comment]
2. error during init, not copying annotation dir
```
cp: cannot stat '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/CARLISLE/.v2.4.1-a/bin/annotation/*': No such file or directory
```

**Comment by slsevilla** [comment]
3. [module purge](https://github.com/CCBR/CARLISLE/blob/36aed6f54204a3105b663f7b278e04389693a417/carlisle#L17C1-L18C1) is unloading ccbrpipeliner
```
[-] Unloading ccbrpipeliner  develop  Thank you for using ccbrpipeliner! 
Pipeline Dir: /gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/CARLISLE/.v2.4.1-a/bin
fatal: not a git repository (or any parent up to mount point /gpfs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by slsevilla** [comment]
4. cant find configs for tests

I don't think we outlined this, but .test dir will need to be copied too
```
sed: can't read /gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/CARLISLE/.v2.4.1-a/bin/.test/samples.tinytest.tsv: No such file or directory
cp: cannot stat '/gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/CARLISLE/.v2.4.1-a/bin/.test/contrasts.tinytest.tsv': No such file or directory
```

**Comment by kelly-sovacool** [comment]
@slsevilla I believe I fixed everything here except the GUI thing since we haven't made one yet.

I was able to submit a testrun to the cluster!

**Comment by slsevilla** [comment]
@kelly-sovacool  - I just ran a test run and everything is working! thanks for the updates!
