### ISSUE TITLE
Consider allowing workdir to already existing during `init`

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/CARLISLE#97]
`carlisle --runmode=init --workdir=.`

```
Pipeline Dir: /gpfs/gsfs10/users/CCBR_Pipeliner/Pipelines/CARLISLE/.v2.4.1-a/bin
Git Commit/Tag: 57f7d79ff4bd5062ff776134d69346250328d148        v2.4.0-6-g57f7d79
Working Dir: /gpfs/gsfs12/users/sovacoolkl/carlisle_test

  #
  #
  #
    Folder /gpfs/gsfs12/users/sovacoolkl/carlisle_test already exists!
```

Perhaps instead it could throw a warning if the directory isn't empty?

**Comment by slsevilla** [comment]
Since we're overwriting the configs etc on init, concern is that you could overwrite a previous runs information, which you don't want to do. We could add an archive step here or something similar to ensure we don't lose the previous configs

**Comment by kelly-sovacool** [comment]
Gotcha. Maybe we could add a `-f/--force` flag to allow it to overwrite the dir, otherwise fail?

**Comment by slsevilla** [comment]
Love that idea! Def works.
